### ISSUE TITLE
Change agent type

### ISSUE THREAD

**Issue by Ketsuko** [dadung/G2D#2]
Hey! 
First of all, congrats for your awesome job!
I was wondering, is it possible to change the camera agent and choose a car instead of a pedestrian?
Is there a way to automate such a process?

Thank you!

**Comment by dzungdoan6** [comment]
Hello, 

Sorry for late reply, just back from a long holiday

+ "Is it possible to change the camera agent and choose a car instead of a pedestrian?"
I think it is possible, some helpful functions from Scripthook you can look into are:
PED::IS_PED_IN_ANY_VEHICLE
PED::GET_VEHICLE_PED_IS_USING
I will keep in mind your suggestion and develop this function later. Actually, I am struggling to submit research papers to graduate from PhD, so I am quite lazy to update G2D, really sorry :( 

+ "Is there a way to automate such a process?"
Can you please clarify what "process" is here?

Thank you!
